version: "3"
services:
  web:
    image: nginx
    ports:
      - "8800:80"
    volumes:
      - ./:/var/www/html
      - ./env/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./env/nginx/log:/var/log/nginx
    networks:
      - lnmpnet
  php:
    hostname: php
    restart: always
    container_name: php
    build:
      context: ./env/packages/php
      dockerfile: Dockerfile
    ports:
      - "9999:9000"
    volumes:
      - ./:/var/www/html
      - ./env/php:/usr/local/etc/php
    networks:
      - lnmpnet
  mysql: # 添加 mysql 服务
    image: mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - MYSQL_ROOT_PASSWORD=123456 # 设置 root 用户密码
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M; # 设置编码
    ports:
      - 3366:3306
    volumes:
      - ./env/mysql/my.cnf:/etc/my.cnf
      - ./env/mysql/log:/var/log/mysql
      - ./env/mysql/data:/var/lib/mysql
    networks:
      - lnmpnet
networks:
  lnmpnet: